from ..const import *
from .structs import ControlMapping, FileHeaderPacket, SequencePacket
from .framer import HSLinkFramer
import logging

log = logging.getLogger(__name__)

class HSLinkSession:
    """
    The core HS/Link state machine.
    Ties the Transport, the Framer, and the Packet logic together.
    """
    def __init__(self, transport):
        self.transport = transport
        self.framer = HSLinkFramer(transport)
        
        # Callbacks that external applications can hook into for M2M communication
        self.on_chat_received = None

    def send_chat(self, message: bytes):
        """
        Sends an out-of-band M2M message using the Chat Channel ('H' packet).
        """
        self.framer.send_packet(PACK_CHAT_BLOCK, message)

    def step(self):
        """
        Executes one tick of the cooperative event loop.
        Processes any incoming packets generated by the Framer.
        """
        for pkt_type, payload in self.framer.read_packets():
            self._handle_packet(pkt_type, payload)

    def _handle_packet(self, pkt_type: bytes, payload: bytes):
        """
        Routes the unescaped, CRC-verified packet payload to the state machine logic.
        """
        if pkt_type == PACK_CHAT_BLOCK:
            if self.on_chat_received:
                self.on_chat_received(payload)
            else:
                log.info(f"[CHAT/M2M] {payload!r}")
                
        elif pkt_type == PACK_OPEN_FILE:
            header = FileHeaderPacket.unpack(payload)
            log.info(f"Peer requested to open file: {header['name'].decode('utf-8', 'ignore')}")
            
        elif pkt_type == PACK_READY:
            log.info("Received Handshake: READY (R)")
            
        elif pkt_type == PACK_READY_RECV:
            log.info("Received Handshake: READY_RECV (Q)")
            
        else:
            log.debug(f"Unhandled packet type: {pkt_type!r} length: {len(payload)}")

    def loop(self):
        """
        Blocks and runs the session until carrier is lost (socket/pipe closed).
        """
        # transport.idle() returns True as long as the pipe is alive
        while self.transport.idle(timeout=0.01):
            self.step()
