import time
import os
from ..const import *
from .structs import ControlMapping, FileHeaderPacket, SequencePacket, ResumeVerifyPacket, ExtNakPacket, FileHeaderPacket, SequencePacket
from .framer import HSLinkFramer
from ..tools import unix_to_dos_time, dos_to_unix_time, crc32
import logging

log = logging.getLogger(__name__)

class HSLinkSession:
    """
    The core HS/Link state machine.
    Ties the Transport, the Framer, and the Packet logic together.
    """
    def __init__(self, transport):
        self.transport = transport
        self.framer = HSLinkFramer(transport)
        
        # Callbacks that external applications can hook into for M2M communication
        self.on_chat_received = None

        # State Machine Core
        self.state = "INIT"
        self.last_tx_time = 0
        
        # File Receiver State
        self.recv_dir = "."
        self.recv_file = None
        self.recv_fd = None
        self.recv_batch_index = 0
        self.recv_expected_block = 0
        self.recv_file_time = 0
        self.files_to_send = []
        self.current_file = None
        self.current_fd = None
        self.batch_index = 0
        self.total_blocks = 0
        self.next_block_num = 0
        self.unacked_blocks = {}
        self.window_size = 64  # Maximum packets in-flight (High since TCP handles true flow control)

    def add_files(self, filepaths):
        """Adds local files to the transmit queue."""
        self.files_to_send.extend(filepaths)

    def send_chat(self, message: bytes):
        """
        Sends an out-of-band M2M message using the Chat Channel ('H' packet).
        """
        self.framer.send_packet(PACK_CHAT_BLOCK, message)

    def step(self):
        """
        Executes one tick of the cooperative event loop.
        Processes any incoming packets generated by the Framer.
        """
        for pkt_type, payload in self.framer.read_packets():
            self._handle_packet(pkt_type, payload)

        now = time.time()
        
        # Handshake sequence loop
        if self.state == "INIT":
            if now - self.last_tx_time > 1.0: # Broadcast handshake ping every second
                log.debug("Sending Handshake (R and Q)...")
                self.framer.send_packet(PACK_READY, b"")
                self.framer.send_packet(PACK_READY_RECV, b"")
                self.last_tx_time = now
                
        # Sender File Transfer sequence loop
        elif self.state == "TRANSFERRING":
            self._pump_sender()

    def _pump_sender(self):
        """Pumps the sliding window file sender queue."""
        # If we are done, don't pump
        if self.state == "DONE" or getattr(self, '_sent_z', False):
            return
            
        # 1. Start a new file if our pipeline is idle
        if not self.current_file:
            if not self.files_to_send:
                # Only signal done if we actually sent files (or initiated as a sender)
                if self.batch_index > 0:
                    log.info("All files transmitted.")
                    self.framer.send_packet(PACK_TRANSMIT_DONE, b"")
                    self._sent_z = True
                # Wait for the peer to send Z to complete
                return
            self._open_next_file()

        # ARQ Timeout Logic: Resend oldest unacked block if we've been waiting too long
        if self.unacked_blocks:
            current_time = time.time()
            if not hasattr(self, 'last_arq_time'):
                self.last_arq_time = current_time
            elif current_time - self.last_arq_time > 2.0:
                oldest_block = min(self.unacked_blocks.keys())
                log.warning(f"ARQ Timeout! Resending block {oldest_block}")
                
                stored_payload = self.unacked_blocks[oldest_block]
                # stored_payload already contains Seq + Map + Data because of our previous patch
                self.framer.send_packet(PACK_DATA_BLOCK_SMD, stored_payload)
                self.last_arq_time = current_time

        # 2. Fill the sliding window with packets up to window_size
        while len(self.unacked_blocks) < self.window_size and self.next_block_num < self.total_blocks:
            chunk = self.current_fd.read(MAX_BLOCK_SIZE)
            if not chunk:
                break
                
            # Send D (Seq+Map+Data) for all blocks to guarantee sequence robustness over noisy lines.
            seq_bytes = SequencePacket.pack(self.batch_index, self.next_block_num)
            map_bytes = ControlMapping.pack(XON_CHR, XOFF_CHR, DLE_CHR, START_PACKET_CHR, END_PACKET_CHR)
            payload = seq_bytes + map_bytes + chunk
            
            self.unacked_blocks[self.next_block_num] = payload
            self.framer.send_packet(PACK_DATA_BLOCK_SMD, payload)
                
            self.next_block_num += 1

        # 3. Handle End of File (Once all blocks are sent AND acknowledged)
        if self.next_block_num >= self.total_blocks and not self.unacked_blocks:
            log.info(f"File {self.current_file} successfully transferred.")
            self.framer.send_packet(PACK_CLOSE_FILE, b"")
            self.current_fd.close()
            self.current_file = None
            self.batch_index += 1

    def _open_next_file(self):
        """Prepares the File Header for the next file in queue."""
        filepath = self.files_to_send.pop(0)
        st = os.stat(filepath)
        filename = os.path.basename(filepath).encode('utf-8')
        dos_time = unix_to_dos_time(st.st_mtime)
        blocks = (st.st_size + MAX_BLOCK_SIZE - 1) // MAX_BLOCK_SIZE if st.st_size > 0 else 0
        
        log.info(f"Opening file: {filepath} ({st.st_size} bytes)")
        
        header = FileHeaderPacket.pack(
            name=filename,
            size=st.st_size,
            blocks=blocks,
            block_size=MAX_BLOCK_SIZE,
            time_dos=dos_time,
            batch=self.batch_index
        )
        
        self.framer.send_packet(PACK_OPEN_FILE, header)
        self.current_file = filepath
        self.current_fd = open(filepath, 'rb')
        self.total_blocks = blocks
        self.next_block_num = 0
        self.unacked_blocks.clear()

    def _handle_packet(self, pkt_type: bytes, payload: bytes):
        """
        Routes the unescaped, CRC-verified packet payload to the state machine logic.
        """
        if pkt_type == PACK_CHAT_BLOCK:
            if self.on_chat_received:
                self.on_chat_received(payload)
            else:
                log.info(f"[CHAT/M2M] {payload!r}")
                
        elif pkt_type == PACK_READY or pkt_type == PACK_READY_RECV:
            if self.state == "INIT":
                self.state = "TRANSFERRING"
                log.info("Handshake sync complete. Connection established.")
                # We should ping back once immediately so the other side knows we synced
                self.framer.send_packet(PACK_READY, b"")
                self.framer.send_packet(PACK_READY_RECV, b"")
                
                # If we are the receiver and have no files to send, we should immediately signal that our send queue is empty
                if not self.files_to_send:
                    log.info("Send queue empty, sending PACK_TRANSMIT_DONE (Z) immediately.")
                    self.framer.send_packet(PACK_TRANSMIT_DONE, b"")
                
        elif pkt_type == PACK_ACK_BLOCK:
            seq = SequencePacket.unpack(payload)
            if seq['batch'] == self.batch_index:
                ack_block = seq['block']
                # Remove the acknowledged block and any older blocks in-flight
                cleared = [k for k in self.unacked_blocks.keys() if k <= ack_block]
                for k in cleared:
                    del self.unacked_blocks[k]
                self.last_arq_time = time.time()

        elif pkt_type == PACK_NAK_BLOCK:
            seq = SequencePacket.unpack(payload)
            if seq['batch'] == self.batch_index:
                nak_block = seq['block']
                if nak_block in self.unacked_blocks:
                    log.warning(f"Received NAK for block {nak_block}. Resending.")
                    # Always resend using D (Seq+Map+Data)
                    stored_payload = self.unacked_blocks[nak_block]
                    self.framer.send_packet(PACK_DATA_BLOCK_SMD, stored_payload)
                
        elif pkt_type == PACK_OPEN_FILE:
            header = FileHeaderPacket.unpack(payload)
            filename = header['name'].decode('utf-8', 'ignore')
            log.info(f"Peer requested to open file: {filename} ({header['size']} bytes)")
            
            filepath = os.path.join(self.recv_dir, filename)
            self.recv_file = filepath
            self.recv_batch_index = header['batch']
            self.recv_expected_block = 0
            self.recv_file_time = dos_to_unix_time(header['time'])
            
            # Crash Recovery & Skip Logic
            if os.path.exists(filepath):
                st = os.stat(filepath)
                if st.st_size == header['size']:
                    log.info(f"File {filename} exists and matches size. Sending SKIP (K).")
                    self.framer.send_packet(PACK_SKIP_FILE, b"")
                    return
                elif st.st_size < header['size']:
                    log.info(f"File {filename} partially exists. Hashing blocks to send VERIFY (V).")
                    with open(filepath, 'rb') as f:
                        count = 0
                        crcs = bytearray()
                        while count < 100:
                            chunk = f.read(MAX_BLOCK_SIZE)
                            if len(chunk) < MAX_BLOCK_SIZE:
                                break
                            crc_val = crc32(chunk)
                            crcs.extend(crc_val.to_bytes(4, 'little'))
                            count += 1
                        
                        if count > 0:
                            v_payload = ResumeVerifyPacket.pack_header(0, count) + crcs
                            self.framer.send_packet(PACK_VERIFY_BLOCK, v_payload)
                            self.recv_expected_block = count
                            self.recv_fd = open(filepath, 'ab')
                            return
                            
            # Open fresh
            self.recv_fd = open(filepath, 'wb')
            
        elif pkt_type == PACK_DATA_BLOCK_SMD:
            # Type D: Sequence + Mapping + Data
            seq_size = SequencePacket.SIZE
            map_size = ControlMapping.SIZE
            
            seq = SequencePacket.unpack(payload[:seq_size])
            chunk = payload[seq_size + map_size:]
            
            if seq['batch'] == self.recv_batch_index:
                if seq['block'] == self.recv_expected_block:
                    if self.recv_fd:
                        self.recv_fd.write(chunk)
                    self.recv_expected_block += 1
                    
                    # ACK the successfully received block
                    ack_payload = SequencePacket.pack(seq['batch'], seq['block'])
                    self.framer.send_packet(PACK_ACK_BLOCK, ack_payload)
                elif seq['block'] > self.recv_expected_block:
                    # We missed a block! Send a NAK for the expected block
                    log.warning(f"Out of order block {seq['block']} received, expecting {self.recv_expected_block}. Sending NAK.")
                    nak_payload = SequencePacket.pack(seq['batch'], self.recv_expected_block)
                    self.framer.send_packet(PACK_NAK_BLOCK, nak_payload)
                else:
                    # Duplicate block (seq < expected). Just ACK it again so sender can move on
                    ack_payload = SequencePacket.pack(seq['batch'], seq['block'])
                    self.framer.send_packet(PACK_ACK_BLOCK, ack_payload)
                
        elif pkt_type == PACK_DATA_BLOCK_D:
            # Type F: Data Only (Optimization Cascade)
            # Since F blocks do NOT contain a sequence number, they implicitly mean "expected_block"
            # But wait, if an F block is corrupted, we won't know until the NEXT D block?
            # Actually, the framer throws away the corrupted F block.
            # The sender won't get an ACK for it. The sender will eventually timeout or we will send NAK.
            # For now, we assume if we get an F block it is the expected block.
            chunk = payload
            if self.recv_fd:
                self.recv_fd.write(chunk)
                
            ack_payload = SequencePacket.pack(self.recv_batch_index, self.recv_expected_block)
            self.framer.send_packet(PACK_ACK_BLOCK, ack_payload)
            self.recv_expected_block += 1
            
        elif pkt_type == PACK_EXTNAK_BLOCK:
            # Sub-Block NAKs (M Packets)
            # Over TCP, we treat this exactly like a full-block NAK for reliability.
            header = ExtNakPacket.unpack_header(payload)
            if header['batch'] == self.batch_index:
                nak_block = header['block']
                if nak_block in self.unacked_blocks:
                    log.warning(f"Received ExtNAK for block {nak_block}. Resending full block.")
                    stored_payload = self.unacked_blocks[nak_block]
                    self.framer.send_packet(PACK_DATA_BLOCK_SMD, stored_payload)
                    
        elif pkt_type == PACK_SKIP_FILE:
            log.info(f"Peer requested SKIP for file: {self.current_file}")
            self.unacked_blocks.clear()
            self.next_block_num = self.total_blocks
            
        elif pkt_type == PACK_VERIFY_BLOCK:
            # Resume verification (V)
            v_header = ResumeVerifyPacket.unpack_header(payload)
            base_block = v_header['base_block']
            count = v_header['count']
            log.info(f"Peer requested VERIFY for {count} blocks starting at {base_block}.")
            
            # Read our local file to verify the CRCs
            self.current_fd.seek(base_block * MAX_BLOCK_SIZE)
            verified = 0
            offset = ResumeVerifyPacket.HEADER_SIZE
            for _ in range(count):
                chunk = self.current_fd.read(MAX_BLOCK_SIZE)
                if not chunk: break
                expected_crc = int.from_bytes(payload[offset:offset+4], 'little')
                if crc32(chunk) == expected_crc:
                    verified += 1
                    offset += 4
                else:
                    break
                    
            log.info(f"Verified {verified} blocks. Seeking sender to block {base_block + verified}.")
            self.next_block_num = base_block + verified
            self.current_fd.seek(self.next_block_num * MAX_BLOCK_SIZE)
            self.unacked_blocks.clear()
            
            # Send SEEK (S) to align the receiver
            seq_payload = SequencePacket.pack(self.batch_index, self.next_block_num)
            self.framer.send_packet(PACK_SEEK_BLOCK, seq_payload)
            
        elif pkt_type == PACK_SEEK_BLOCK:
            seq = SequencePacket.unpack(payload)
            if seq['batch'] == self.recv_batch_index:
                log.info(f"Sender seeking to block {seq['block']}")
                self.recv_expected_block = seq['block']
                
        elif pkt_type == PACK_CLOSE_FILE:
            if self.recv_fd:
                self.recv_fd.close()
                self.recv_fd = None
                log.info(f"File {self.recv_file} successfully received and closed.")
                if self.recv_file_time:
                    try:
                        os.utime(self.recv_file, (time.time(), self.recv_file_time))
                    except Exception as e:
                        log.warning(f"Could not apply DOS timestamp to {self.recv_file}: {e}")
                self.recv_file = None
                
        elif pkt_type == PACK_TRANSMIT_DONE:
            log.info("Peer signaled all files transmitted (Z).")
            # If we are also not sending anything, we can gracefully complete
            if not self.files_to_send and not self.current_file:
                log.info("Receive queue empty, transitioning to DONE.")
                self.state = "DONE"
                
                # If we were strictly a receiver, let's also tell the sender we are done 
                # (so it doesn't wait indefinitely if it finished sending but hadn't received our Z)
                self.framer.send_packet(PACK_TRANSMIT_DONE, b"")
                
    def loop(self):
        """
        Blocks and runs the session until carrier is lost or session naturally completes.
        """
        while self.transport.idle(timeout=0.01):
            self.step()
            
            # If we've successfully finished our side of the send, sleep briefly to flush and exit.
            if self.state == "DONE":
                time.sleep(0.5)
                # Ensure the transport knows we're done so it closes down
                self.transport.carrier_lost = True
                break
