import struct

START_PACKET_CHR = 0x02
END_PACKET_CHR = 0x1B
DLE_CHR = 0x1E
XON_CHR = 0x11
XOFF_CHR = 0x13
CAN_CHR = 0x18

# Packet types
PACK_ACK_BLOCK = b'A'
PACK_CLOSE_FILE = b'C'
PACK_DATA_BLOCK_SMD = b'D'
PACK_DATA_BLOCK_MD = b'E'
PACK_DATA_BLOCK_D = b'F'
PACK_CHAT_BLOCK = b'H'
PACK_SKIP_FILE = b'K'
PACK_EXTNAK_BLOCK = b'M'
PACK_NAK_BLOCK = b'N'
PACK_OPEN_FILE = b'O'
PACK_RESET_FILE = b'P'
PACK_READY_RECV = b'Q'
PACK_READY = b'R'
PACK_SEEK_BLOCK = b'S'
PACK_VERIFY_BLOCK = b'V'
PACK_TRANSMIT_DONE = b'Z'

# Limits
MAX_BLOCK_SIZE = 4096
DEF_CRC_SIZE = 3 # 24-bit

# Timeouts
ACK_TIMEOUT = 20000
MAX_TIMEOUT = 4
RCV_TIMEOUT_N = 22000
RCV_TIMEOUT_P = 11000
READY_TIMEOUT = 120000
ENQ_TIMEOUT = 5000
VERIFY_TIMEOUT = 60000
TERMINATE_TIMEOUT = 500
CHAT_TIMEOUT = 2000
CHAT_CLOSE = 30000

